### ISSUE TITLE
Indent line style

### ISSUE THREAD

**Issue by sifangli** [nathanaelkane/vim-indent-guides#121] opened 2017-02-23 21:16 UTC
I love the thin dotted line like this one:
https://camo.githubusercontent.com/77b20e2e707ac1d85fd8bc12f16b5b7b7e72e186/687474703a2f2f692e696d6775722e636f6d2f4b566930542e6a7067

Can you support that? Thanks!

-Sifang

**Comment by sdothum** [comment] 2017-03-07 17:43
I used [indentline](https://github.com/Yggdroot/indentLine) which provides what you are requesting before switching to vim-indent-guides myself.

**Comment by nathanaelkane** [comment] 2017-03-07 21:34
I'd love to have this functionality, but it's not a priority right now. The [indentLine](https://github.com/Yggdroot/indentLine) plugin is definitely the way to go if you want this :+1:

Closing as duplicate of #46.

**Closed by nathanaelkane** 2017-03-07 21:34 UTC
