### ISSUE TITLE
Use foreground char separator instead of a background color

### ISSUE THREAD

**Issue by nowox** [nathanaelkane/vim-indent-guides#83] opened 2015-04-10 12:55 UTC
I will consider this plugin remarkable if instead of a colored background blank char we use a colored |.

I think this might be possible with the conceal feature. 

```c
void main() {
   for(;;) {
   |   if(foo) {
   |   |   bar = true;
   |   }
   }
}
```

**EDIT**
Actually I just found this plugin: https://github.com/Yggdroot/indentLine which does exactly what I was thinking

**Comment by nathanaelkane** [comment] 2015-04-27 05:22
I'd love to have this functionality, but it's not a priority right now. The [indentLine](https://github.com/Yggdroot/indentLine) plugin is definitely the way to go if you want this :+1:

Closing as duplicate of #46.

**Closed by nathanaelkane** 2015-04-27 05:22 UTC
